module.exports = {
    GENERATE_FROM_CONFIG_FILE: 0,
    GENERATE_FROM_USER_INPUTS: 1,
    GENERATE_FROM_CONFIG_FILE_ACTION_TYPE: 'generateCRUDByConfig',
    GENERATE_FROM_USER_INPUTS_ACTION_TYPE: 'generateCRUDByInput',
}